# the following tag is no longer required, i.e. "sudo" has been deprecated and should not longer be used
# .. # tell travis-ci that sudo is required
# .. sudo: required

# a bit unclear why this is required:
language: generic
# tell travis-ci that we need a running instance of docker
services:
    - docker

# tell travis-ci that before anything is really done
# (e.g. running test etc.), we want to build our image
# The image is tagged to have a stable identifier for it
# Note: 
# - the image has the name of the github repository
#   this is not required; it could be any tag; the tag is only used within travis-ci
#   so it could be -t hubbledibubble
before_install:
    - docker build -t vagandon/docker-react -f dockerfile.dev .

# Now we tell travis-ci how to run the test-suite.
# Note:
# - with "-e CI=true" we are setting an environment variable CI to true
# - this forces Jest to run in CI mode and execute tests only once 
#   without entering the watch mode
script:
    - docker run -e CI=true vagandon/docker-react npm run test

# The deploy-information for travis-ci
deploy:
    # provider: travis-ci has a number of pre-configured providers, one
    # of them is Elastic Beanstalk, hence we can directly identify it
    provider: elasticbeanstalk
    # region: look into the app-url provided by aws to identify the region
    region: "eu-central-1"
    # app and env: the name of the application and its environment as defined in aws
    app: "docker-react"
    env: "DockerReact-env"
    # bucket_name: the S3 bucket where travis-ci can store the code
    # - go to the S3 service in AWS to get the S3 bucket name
    bucket_name: "elasticbeanstalk-eu-central-1-304092658149"
    # bucket_path: the path of the folder inside the bucket to which travis should
    # deploy the code
    bucket_path: "docker-react"
    # on: this specifies, which eventy cause travis-ci to deploy. Here, this should
    # only be done when a merge into the master branch happens
    on:
        branch: master
    # Credentials:
    access_key_id: $Access_Key_ID
    secret_access_key: $Secret_Access_Key
