# docker-compose file for illustrative purposes
# note: services have their physical "manifestation" in containers
# - ports mapping in the dev-service is to reach the server via the browser outside the container
# - volume mapping allows to change the app.js during dev and app.test.js durin tests on the fly without restart
version: '3'
services:
    react_app_dev: 
        build:
            context: .
            dockerfile: dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app
        stdin_open: true
    # 2nd service for tests
    # - is very similar to the react_app service
    # - doesn't need port mapping
    # - overrides the default start command
    react_app_test: 
        build:
            context: .
            dockerfile: dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]
        stdin_open: true